language: java
services:
  - docker
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  - docker build -t quiz .
  - docker run -d -p 8080:8080 quiz
  - docker ps -a